import { execFileSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeFileSync } from 'node:fs';

/**
 * When each page's content last changed, measured from this repository.
 *
 * The sitemap's `lastmod` is a promise to a crawler, and a build date is a
 * broken one: it moves every deploy, including deploys that change nothing a
 * reader would see, and Google stops trusting a `lastmod` that behaves that
 * way. So the date comes from Git — the last commit that touched any of the
 * files a page is actually built from.
 *
 * The result is written to `src/lib/content/content-log.ts` and committed,
 * the same arrangement as `project-history.ts`: Vercel clones shallowly, so
 * asking Git at build time would answer with whatever history the clone
 * happened to include.
 *
 * Regenerate with `npm run content:log`, after changing page copy.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const WEB = join(HERE, '..');
const REPO = join(WEB, '..');
const OUT = join(WEB, 'src', 'lib', 'content', 'content-log.ts');

/**
 * What each page is made of. Copy and route component both count: a case file
 * changes when its words change and when the page that prints them changes.
 */
const PAGES = {
	home: ['web/src/routes/[lang=lang]/+page.svelte', 'web/src/lib/content/site.ts'],
	caseFile: [
		'web/src/routes/[lang=lang]/missions/[slug]/+page.svelte',
		'web/src/lib/components/comic-reader/CaseFilePage.svelte',
		'web/src/lib/content/projects.ts',
		'web/src/lib/content/project-history.ts'
	]
};

/** The last commit date, `YYYY-MM-DD`, across a set of paths. */
function lastChanged(paths) {
	const out = execFileSync('git', ['log', '-1', '--format=%cs', '--', ...paths], {
		cwd: REPO,
		encoding: 'utf8'
	}).trim();

	if (!out) throw new Error(`No commit touches ${paths.join(', ')} — is the clone shallow?`);
	return out;
}

const dates = Object.fromEntries(
	Object.entries(PAGES).map(([page, paths]) => [page, lastChanged(paths)])
);

const body = `/**
 * When each page's content last changed, as Git records it.
 *
 * GENERATED by \`scripts/content-log.mjs\` on ${new Date().toISOString().slice(0, 10)}.
 * Do not edit by hand — rerun \`npm run content:log\`. These dates are the
 * sitemap's \`lastmod\`, so they have to describe the content rather than the
 * deploy that happened to carry it.
 */

export type PageKind = ${Object.keys(dates)
	.map((key) => `'${key}'`)
	.join(' | ')};

/** Last content change per page kind, \`YYYY-MM-DD\`. */
export const contentLog: Record<PageKind, string> = {
${Object.entries(dates)
	.map(([page, date]) => `\t${page}: '${date}'`)
	.join(',\n')}
};
`;

writeFileSync(OUT, body);

for (const [page, date] of Object.entries(dates)) console.log(`${page.padEnd(10)} ${date}`);
console.log(`\nWrote ${OUT.replace(REPO + '/', '')}`);
