/**
 * When each page's content last changed, as Git records it.
 *
 * GENERATED by `scripts/content-log.mjs` on 2026-09-20.
 * Do not edit by hand — rerun `npm run content:log`. These dates are the
 * sitemap's `lastmod`, so they have to describe the content rather than the
 * deploy that happened to carry it.
 */

export type PageKind = 'home' | 'caseFile';

/** Last content change per page kind, `YYYY-MM-DD`. */
export const contentLog: Record<PageKind, string> = {
	home: '2026-09-19',
	caseFile: '2026-09-19'
};
