/**
 * The project log: what the repositories behind each case file say about it.
 *
 * GENERATED by `scripts/project-history.mjs` from the local Git history on
 * 2026-09-24. Do not edit by hand — rerun the script. Aggregates only:
 * dates, counts and the shape of the tree. No code, path or message leaves the
 * machine.
 */

export interface RepositoryLog {
	name: string;
	/** What the repository is: the product, its API, or a native app. */
	kind: 'app' | 'api' | 'native';
	commits: number;
	since: string;
	until: string;
	files: number;
}

export interface ProjectHistory {
	slug: string;
	/** The day the repositories were read, `YYYY-MM-DD`. */
	measuredAt: string;
	/** First and last month with a commit, `YYYY-MM`. */
	since: string;
	until: string;
	commits: number;
	activeMonths: number;
	/** Every month from `since` to `until`, quiet ones included. */
	months: { month: string; commits: number }[];
	repos: RepositoryLog[];
	files: number;
	/** What the tree holds, counted: SvelteKit pages, Nest controllers, Prisma
	 * models, SQL migrations, test files, Swift and Kotlin sources. */
	counts: {
		pages: number;
		controllers: number;
		models: number;
		migrations: number;
		tests: number;
		native: number;
	};
}

export const histories: ProjectHistory[] = [
	{
		slug: 'segispro',
		measuredAt: '2026-09-24',
		since: '2025-11',
		until: '2026-09',
		commits: 799,
		activeMonths: 11,
		months: [
			{
				month: '2025-11',
				commits: 52
			},
			{
				month: '2025-12',
				commits: 60
			},
			{
				month: '2026-01',
				commits: 86
			},
			{
				month: '2026-02',
				commits: 75
			},
			{
				month: '2026-03',
				commits: 58
			},
			{
				month: '2026-04',
				commits: 90
			},
			{
				month: '2026-05',
				commits: 158
			},
			{
				month: '2026-06',
				commits: 79
			},
			{
				month: '2026-07',
				commits: 46
			},
			{
				month: '2026-08',
				commits: 36
			},
			{
				month: '2026-09',
				commits: 59
			}
		],
		repos: [
			{
				name: 'app',
				kind: 'app',
				commits: 620,
				since: '2025-11',
				until: '2026-09',
				files: 335
			},
			{
				name: 'api',
				kind: 'api',
				commits: 179,
				since: '2026-05',
				until: '2026-09',
				files: 1553
			}
		],
		files: 1888,
		counts: {
			pages: 49,
			controllers: 55,
			models: 0,
			migrations: 19,
			tests: 48,
			native: 0
		}
	},
	{
		slug: 'formarpro',
		measuredAt: '2026-09-24',
		since: '2026-05',
		until: '2026-09',
		commits: 93,
		activeMonths: 5,
		months: [
			{
				month: '2026-05',
				commits: 9
			},
			{
				month: '2026-06',
				commits: 10
			},
			{
				month: '2026-07',
				commits: 11
			},
			{
				month: '2026-08',
				commits: 43
			},
			{
				month: '2026-09',
				commits: 20
			}
		],
		repos: [
			{
				name: 'app',
				kind: 'app',
				commits: 56,
				since: '2026-05',
				until: '2026-09',
				files: 455
			},
			{
				name: 'api',
				kind: 'api',
				commits: 37,
				since: '2026-05',
				until: '2026-09',
				files: 640
			}
		],
		files: 1095,
		counts: {
			pages: 78,
			controllers: 47,
			models: 0,
			migrations: 0,
			tests: 42,
			native: 0
		}
	},
	{
		slug: 'transmeralda',
		measuredAt: '2026-09-24',
		since: '2025-10',
		until: '2026-09',
		commits: 1137,
		activeMonths: 12,
		months: [
			{
				month: '2025-10',
				commits: 6
			},
			{
				month: '2025-11',
				commits: 1
			},
			{
				month: '2025-12',
				commits: 8
			},
			{
				month: '2026-01',
				commits: 20
			},
			{
				month: '2026-02',
				commits: 38
			},
			{
				month: '2026-03',
				commits: 75
			},
			{
				month: '2026-04',
				commits: 150
			},
			{
				month: '2026-05',
				commits: 39
			},
			{
				month: '2026-06',
				commits: 107
			},
			{
				month: '2026-07',
				commits: 173
			},
			{
				month: '2026-08',
				commits: 181
			},
			{
				month: '2026-09',
				commits: 339
			}
		],
		repos: [
			{
				name: 'transmeralda · app',
				kind: 'app',
				commits: 502,
				since: '2025-10',
				until: '2026-09',
				files: 682
			},
			{
				name: 'transmeralda · api',
				kind: 'api',
				commits: 207,
				since: '2026-05',
				until: '2026-09',
				files: 778
			},
			{
				name: 'cotransmeq · app',
				kind: 'app',
				commits: 257,
				since: '2026-02',
				until: '2026-09',
				files: 625
			},
			{
				name: 'cotransmeq · api',
				kind: 'api',
				commits: 171,
				since: '2026-02',
				until: '2026-09',
				files: 686
			}
		],
		files: 2771,
		counts: {
			pages: 168,
			controllers: 104,
			models: 292,
			migrations: 111,
			tests: 142,
			native: 0
		}
	},
	{
		slug: 'developer-os',
		measuredAt: '2026-09-24',
		since: '2026-08',
		until: '2026-09',
		commits: 114,
		activeMonths: 2,
		months: [
			{
				month: '2026-08',
				commits: 104
			},
			{
				month: '2026-09',
				commits: 10
			}
		],
		repos: [
			{
				name: 'developer-os',
				kind: 'native',
				commits: 114,
				since: '2026-08',
				until: '2026-09',
				files: 423
			}
		],
		files: 423,
		counts: {
			pages: 0,
			controllers: 0,
			models: 0,
			migrations: 0,
			tests: 105,
			native: 350
		}
	},
	{
		slug: 'gym-vancouver',
		measuredAt: '2026-09-24',
		since: '2026-08',
		until: '2026-09',
		commits: 80,
		activeMonths: 2,
		months: [
			{
				month: '2026-08',
				commits: 34
			},
			{
				month: '2026-09',
				commits: 46
			}
		],
		repos: [
			{
				name: 'app',
				kind: 'app',
				commits: 80,
				since: '2026-08',
				until: '2026-09',
				files: 448
			}
		],
		files: 448,
		counts: {
			pages: 32,
			controllers: 0,
			models: 30,
			migrations: 12,
			tests: 29,
			native: 0
		}
	},
	{
		slug: 'manejo-comentado',
		measuredAt: '2026-09-24',
		since: '2026-09',
		until: '2026-09',
		commits: 112,
		activeMonths: 1,
		months: [
			{
				month: '2026-09',
				commits: 112
			}
		],
		repos: [
			{
				name: 'platform',
				kind: 'app',
				commits: 112,
				since: '2026-09',
				until: '2026-09',
				files: 468
			}
		],
		files: 468,
		counts: {
			pages: 19,
			controllers: 16,
			models: 17,
			migrations: 11,
			tests: 31,
			native: 126
		}
	},
	{
		slug: 'viziona-cines',
		measuredAt: '2026-09-24',
		since: '2026-09',
		until: '2026-09',
		commits: 177,
		activeMonths: 1,
		months: [
			{
				month: '2026-09',
				commits: 177
			}
		],
		repos: [
			{
				name: 'storefront',
				kind: 'app',
				commits: 177,
				since: '2026-09',
				until: '2026-09',
				files: 322
			}
		],
		files: 322,
		counts: {
			pages: 22,
			controllers: 0,
			models: 0,
			migrations: 0,
			tests: 3,
			native: 0
		}
	}
];

/** Every month from `from` to `to` inclusive, as `YYYY-MM`. */
export function monthSpan(from: string, to: string): string[] {
	const out: string[] = [];
	let [year, month] = from.split('-').map(Number);
	const [endYear, endMonth] = to.split('-').map(Number);
	while (year < endYear || (year === endYear && month <= endMonth)) {
		out.push(`${year}-${String(month).padStart(2, '0')}`);
		month += 1;
		if (month > 12) {
			month = 1;
			year += 1;
		}
	}
	return out;
}

export function historyOf(slug: string): ProjectHistory | undefined {
	return histories.find((history) => history.slug === slug);
}
