/**
 * The project log: what the repositories behind each case file say about it.
 *
 * GENERATED by `scripts/project-history.mjs` from the local Git history on
 * 2026-10-06. Do not edit by hand — rerun the script. Aggregates only:
 * dates, counts and the shape of the tree. No code, path or message leaves the
 * machine.
 */

export interface RepositoryLog {
	name: string;
	/** What the repository is: product app, API, native app or extension. */
	kind: 'app' | 'api' | 'native' | 'extension';
	commits: number;
	since: string;
	until: string;
	files: number;
}

export interface ProjectHistory {
	slug: string;
	/** The day the repositories were read, `YYYY-MM-DD`. */
	measuredAt: string;
	/** First and last month with a commit, `YYYY-MM`. */
	since: string;
	until: string;
	commits: number;
	activeMonths: number;
	/** Every month from `since` to `until`, quiet ones included. */
	months: { month: string; commits: number }[];
	repos: RepositoryLog[];
	files: number;
	/** What the tree holds, counted: SvelteKit pages, Nest controllers, Prisma
	 * models, SQL migrations, test files and native sources. */
	counts: {
		pages: number;
		controllers: number;
		models: number;
		migrations: number;
		tests: number;
		native: number;
	};
}

export const histories: ProjectHistory[] = [
	{
		slug: 'segispro',
		measuredAt: '2026-10-06',
		since: '2025-11',
		until: '2026-10',
		commits: 886,
		activeMonths: 12,
		months: [
			{
				month: '2025-11',
				commits: 52
			},
			{
				month: '2025-12',
				commits: 60
			},
			{
				month: '2026-01',
				commits: 86
			},
			{
				month: '2026-02',
				commits: 75
			},
			{
				month: '2026-03',
				commits: 58
			},
			{
				month: '2026-04',
				commits: 90
			},
			{
				month: '2026-05',
				commits: 158
			},
			{
				month: '2026-06',
				commits: 79
			},
			{
				month: '2026-07',
				commits: 46
			},
			{
				month: '2026-08',
				commits: 36
			},
			{
				month: '2026-09',
				commits: 115
			},
			{
				month: '2026-10',
				commits: 31
			}
		],
		repos: [
			{
				name: 'app',
				kind: 'app',
				commits: 669,
				since: '2025-11',
				until: '2026-10',
				files: 361
			},
			{
				name: 'api',
				kind: 'api',
				commits: 217,
				since: '2026-05',
				until: '2026-10',
				files: 1632
			}
		],
		files: 1993,
		counts: {
			pages: 49,
			controllers: 60,
			models: 0,
			migrations: 19,
			tests: 76,
			native: 0
		}
	},
	{
		slug: 'formarpro',
		measuredAt: '2026-10-06',
		since: '2026-05',
		until: '2026-10',
		commits: 111,
		activeMonths: 6,
		months: [
			{
				month: '2026-05',
				commits: 9
			},
			{
				month: '2026-06',
				commits: 10
			},
			{
				month: '2026-07',
				commits: 11
			},
			{
				month: '2026-08',
				commits: 43
			},
			{
				month: '2026-09',
				commits: 31
			},
			{
				month: '2026-10',
				commits: 7
			}
		],
		repos: [
			{
				name: 'app',
				kind: 'app',
				commits: 69,
				since: '2026-05',
				until: '2026-10',
				files: 489
			},
			{
				name: 'api',
				kind: 'api',
				commits: 42,
				since: '2026-05',
				until: '2026-10',
				files: 670
			}
		],
		files: 1159,
		counts: {
			pages: 85,
			controllers: 50,
			models: 0,
			migrations: 0,
			tests: 50,
			native: 0
		}
	},
	{
		slug: 'transmeralda',
		measuredAt: '2026-10-06',
		since: '2025-10',
		until: '2026-10',
		commits: 1603,
		activeMonths: 13,
		months: [
			{
				month: '2025-10',
				commits: 6
			},
			{
				month: '2025-11',
				commits: 1
			},
			{
				month: '2025-12',
				commits: 8
			},
			{
				month: '2026-01',
				commits: 20
			},
			{
				month: '2026-02',
				commits: 38
			},
			{
				month: '2026-03',
				commits: 75
			},
			{
				month: '2026-04',
				commits: 150
			},
			{
				month: '2026-05',
				commits: 39
			},
			{
				month: '2026-06',
				commits: 107
			},
			{
				month: '2026-07',
				commits: 173
			},
			{
				month: '2026-08',
				commits: 181
			},
			{
				month: '2026-09',
				commits: 666
			},
			{
				month: '2026-10',
				commits: 139
			}
		],
		repos: [
			{
				name: 'transmeralda · app',
				kind: 'app',
				commits: 616,
				since: '2025-10',
				until: '2026-10',
				files: 780
			},
			{
				name: 'transmeralda · api',
				kind: 'api',
				commits: 288,
				since: '2026-05',
				until: '2026-10',
				files: 855
			},
			{
				name: 'cotransmeq · app',
				kind: 'app',
				commits: 369,
				since: '2026-02',
				until: '2026-10',
				files: 717
			},
			{
				name: 'cotransmeq · api',
				kind: 'api',
				commits: 253,
				since: '2026-02',
				until: '2026-10',
				files: 757
			},
			{
				name: 'transmeralda · mobile',
				kind: 'native',
				commits: 38,
				since: '2026-09',
				until: '2026-10',
				files: 130
			},
			{
				name: 'cotransmeq · mobile',
				kind: 'native',
				commits: 39,
				since: '2026-09',
				until: '2026-10',
				files: 131
			}
		],
		files: 3370,
		counts: {
			pages: 166,
			controllers: 108,
			models: 302,
			migrations: 135,
			tests: 163,
			native: 152
		}
	},
	{
		slug: 'developer-os',
		measuredAt: '2026-10-06',
		since: '2026-08',
		until: '2026-09',
		commits: 114,
		activeMonths: 2,
		months: [
			{
				month: '2026-08',
				commits: 104
			},
			{
				month: '2026-09',
				commits: 10
			}
		],
		repos: [
			{
				name: 'developer-os',
				kind: 'native',
				commits: 114,
				since: '2026-08',
				until: '2026-09',
				files: 423
			}
		],
		files: 423,
		counts: {
			pages: 0,
			controllers: 0,
			models: 0,
			migrations: 0,
			tests: 105,
			native: 350
		}
	},
	{
		slug: 'gym-vancouver',
		measuredAt: '2026-10-06',
		since: '2026-08',
		until: '2026-09',
		commits: 80,
		activeMonths: 2,
		months: [
			{
				month: '2026-08',
				commits: 34
			},
			{
				month: '2026-09',
				commits: 46
			}
		],
		repos: [
			{
				name: 'app',
				kind: 'app',
				commits: 80,
				since: '2026-08',
				until: '2026-09',
				files: 448
			}
		],
		files: 448,
		counts: {
			pages: 32,
			controllers: 0,
			models: 30,
			migrations: 12,
			tests: 29,
			native: 0
		}
	},
	{
		slug: 'manejo-comentado',
		measuredAt: '2026-10-06',
		since: '2026-09',
		until: '2026-09',
		commits: 112,
		activeMonths: 1,
		months: [
			{
				month: '2026-09',
				commits: 112
			}
		],
		repos: [
			{
				name: 'platform',
				kind: 'app',
				commits: 112,
				since: '2026-09',
				until: '2026-09',
				files: 468
			}
		],
		files: 468,
		counts: {
			pages: 19,
			controllers: 16,
			models: 17,
			migrations: 11,
			tests: 31,
			native: 126
		}
	},
	{
		slug: 'viziona-cines',
		measuredAt: '2026-10-06',
		since: '2026-09',
		until: '2026-09',
		commits: 193,
		activeMonths: 1,
		months: [
			{
				month: '2026-09',
				commits: 193
			}
		],
		repos: [
			{
				name: 'storefront',
				kind: 'app',
				commits: 193,
				since: '2026-09',
				until: '2026-09',
				files: 322
			}
		],
		files: 322,
		counts: {
			pages: 22,
			controllers: 0,
			models: 0,
			migrations: 0,
			tests: 3,
			native: 0
		}
	},
	{
		slug: 'interest-pulse',
		measuredAt: '2026-10-06',
		since: '2026-09',
		until: '2026-09',
		commits: 22,
		activeMonths: 1,
		months: [
			{
				month: '2026-09',
				commits: 22
			}
		],
		repos: [
			{
				name: 'extension monorepo',
				kind: 'extension',
				commits: 22,
				since: '2026-09',
				until: '2026-09',
				files: 238
			}
		],
		files: 238,
		counts: {
			pages: 0,
			controllers: 10,
			models: 0,
			migrations: 9,
			tests: 24,
			native: 0
		}
	}
];

/** Every month from `from` to `to` inclusive, as `YYYY-MM`. */
export function monthSpan(from: string, to: string): string[] {
	const out: string[] = [];
	let [year, month] = from.split('-').map(Number);
	const [endYear, endMonth] = to.split('-').map(Number);
	while (year < endYear || (year === endYear && month <= endMonth)) {
		out.push(`${year}-${String(month).padStart(2, '0')}`);
		month += 1;
		if (month > 12) {
			month = 1;
			year += 1;
		}
	}
	return out;
}

export function historyOf(slug: string): ProjectHistory | undefined {
	return histories.find((history) => history.slug === slug);
}
